### ISSUE TITLE
Method to determine whether kotsadm-operator was able to get elevated permissions to deploy CRDS

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kotsadm#1082]
As an application packager, I'd like to configure my application to deploy CRDs along with the application itself. This only works, however, if kotsadm-operator was able to get elevated privileges at the cluster scope. I'd like to be able to query whether this happened *before* deploying my app, because if we don't have permission to add CRDs, then I will need kotsadm to run a preflight check to check those CRDs exist.

Not sure if this is a template function or annotation or what. The acceptance criteria for this story is the ability to dynamically decide whether to either

1. include a preflight check for CRDs and *skip* CRD deploy 
2. deploy CRDs at runtime and *skip* preflight check

and to execute that. I'm not sure if preflight supports conditional evaluation yet but if not then that should part of the scope. We also need to make sure CRDs can be dynamically excluded.

### Example (aspirational)

In preflight.yaml

```
analyzers:
  - customResourceDefinition:
       apiVersion: some.group.com
       kind: myobject
       when: repl{{ not (KotsadmOperatorClusterAdmin) }}
```

In crds.yaml 

```
kind: CustomResourceDefinition
metadata:
  name: myobject
  annotations:
    kots.io/when: repl{{ KotsadmOperatorClusterAdmin }}
```
