### ISSUE TITLE
StatusInformers do not work across Namespaces

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kotsadm#1353]
I've implemented [StatusInformers](https://kots.io/reference/v1beta1/application/#statusinformers) for the multi-namespace app listed in #1352, but they do not appear to detect when the nginx pod in the `hardcoded` namespace becomes ready.

**Comment by emosbaugh** [comment]
@dexhorthy i wasnt able to reproduce this with the following yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: namespace2
```

```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: ethan-kots
spec:
  title: Ethan Kots
  statusInformers:
    - namespace2/deployment/nginx-test
```
