### ISSUE TITLE
Changing config and running kubectl kots upload does not use config values

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/kotsadm#1426]
## Summary

Kots download, changing a config value in the upstream, and kots upload does not apply the config value when released to the resource when using the template function ConfigOption.

## What is expected

The config value will change in the deployed resource

## What happens

The config value doesnt change in the config resource. It does change in the config ui

## Steps to reproduce

1. create the file mysecret.yaml
   ```
   apiVersion: v1
   kind: Secret
   metadata:
     name: mysecret
   type: Opaque
   data:
     password: '{{repl ConfigOption "secret_password" | Base64Encode}}'
   ```
2. add item to config:
   ```
           - name: secret_password
             title: Secret Password
             type: text
             default: this is a secret
   ```
3. Ship your release
4. Run kubectl kots download
5. Edit `upstream/userdata/config.yaml` add `value: this is a new secret` to `secret_password`
6. Run kubectl kots upload
7. Deploy upstream update release
