### ISSUE TITLE
Move gitops config to K8s configmap and secrets

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kotsadm#791]
Currently, kotsadm stores gitops data in it's own postgres database. The private key is encrypted using the admin console's global key, and the rest of the data is stored in a few postgres tables.

As part of the larger effort to mature the gitops implementation, we should move the data out of postgres and store it as native kubernetes objects. 

Why? This helps with moving away from pg in the product (long term plans), but it also allows an easier deployment strategy for anyone who wants to deploy configuration as code. Instead of learning our private GraphQL API, kotsadm installation users will be able to create a config map or secret and deploy it to the cluster.

## Global Config

We currently support only 1 provider (in the 1.5.0 designs). But this isn't fixed forever, it's a v1.5.0 limitation only. 

We should create a secret, in the kotsadm namespace, names `kotsadm-gitops`. It should have the following structure (the values should be properly base64 encoded)

```
apiVersion: v1
kind: Secret
metadata: 
  name: kotsadm-gitops
data:
  provider.0.type: "github enteprise"
  provider.0.hostname: "github.somebigbank.com"
  provider.0.publickey: "BEGIN..."
  provider.0.privatekey: "---"
```

If the secret is not present or does not contain any keys, then gitops is unconfigured globally in the admin console. 
Currently it can only have provider.0.* fields, when configured.

## Repo Config

Each repo can build off of this config by enabling gitops, and specifying a repo, branch, path, and format (-k or -f). This data is not sensitive, and can be stored in a config map, as YAML formatted data. All repo config will be in the same config map.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kotsadm-gitops
data:
  app-slug-1:
    repo: somebigbank/gitops-deploy
    branch: master
    path: /app-1
    format: "single"
```

The kots installer will have to be modified to alter the RBAC policy so that the kotsadm-api process can create, edit, delete, and read this configmap and this secret. https://github.com/replicatedhq/kots/blob/e61e655c1f182ef5d4b25aca36176d99e3a9a91c/pkg/kotsadm/api_objects.go#L15

Additionally, the kurl add-on will need this rbac change also: https://github.com/replicatedhq/kurl/blob/be9b576bded39cb7337f6d6be454dac84c79da00/addons/kotsadm/1.3.0/api.yaml#L5 (only in the 1.5.0 version of the addon)
